# Generated by Django 3.1.2 on 2021-09-22 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_classifier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='analyzed_picture',
            field=models.ImageField(default='not applicable', upload_to=''),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='capillary_density',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='image',
            name='number_of_capillaries',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
