# Generated by Django 3.1.2 on 2021-09-22 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_classifier', '0002_auto_20210922_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='analyzed_picture',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
