# Generated by Django 3.1.2 on 2021-09-22 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_classifier', '0005_auto_20210922_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='picture',
            field=models.ImageField(upload_to='microcirculation_images'),
        ),
    ]
