# Generated by Django 3.1.2 on 2021-09-24 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_classifier', '0006_auto_20210922_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='backend_address',
            field=models.IntegerField(blank=True, default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='image',
            name='picture',
            field=models.ImageField(blank=True, upload_to='microcirculation_images'),
        ),
    ]
