# Generated by Django 3.1.2 on 2021-09-25 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_classifier', '0008_auto_20210924_1919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='analyzed_picture',
            field=models.ImageField(blank=True, upload_to='analyzed_picture'),
        ),
    ]
