# Generated by Django 3.1.2 on 2021-09-27 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_classifier', '0009_auto_20210925_1237'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='capillary_density',
            new_name='capillary_area',
        ),
    ]
