# Generated by Django 3.1.2 on 2021-09-27 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_classifier', '0010_auto_20210927_1117'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='segmented_image',
            field=models.ImageField(blank=True, upload_to='segmented_image'),
        ),
    ]
