# Generated by Django 3.2.5 on 2022-01-12 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('image_classifier', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='number_of_capillaries',
            field=models.IntegerField(blank=True),
        ),
    ]
