# Generated by Django 3.2.5 on 2022-01-12 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image_classifier', '0002_alter_image_number_of_capillaries'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='number_of_capillaries',
            new_name='number_of_cap',
        ),
    ]
